export type FieldType = "text" | "textarea" | "number" | "select" | "date" | "url" | "percent" | "currency" | "phone";

export interface FieldDef {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: string[];
  placeholder?: string;
  hint?: string;
  unit?: string;
}

export interface DocumentDef {
  key: string;
  label: string;
  required: boolean;
  accept: string;
  hint?: string;
  multiple?: boolean;
}

export interface AssetTypeConfig {
  id: string;
  label: string;
  icon: string;
  description: string;
  fields: FieldDef[];
  requiredDocuments: DocumentDef[];
  optionalDocuments: DocumentDef[];
}

export const ASSET_TYPES: AssetTypeConfig[] = [
  {
    id: "real_estate",
    label: "Real Estate",
    icon: "🏢",
    description: "Activos inmobiliarios tokenizables",
    fields: [
      { key: "tipo_de_inmueble", label: "Tipo de inmueble", type: "select", required: true, options: ["Casa", "Departamento", "Oficina", "Local comercial", "Galpón/Depósito", "Terreno", "Hotel/Apart Hotel", "Edificio", "Country/Barrio privado", "Otro"] },
      { key: "destino_del_inmueble", label: "Destino del inmueble", type: "select", options: ["Residencial", "Comercial", "Industrial", "Mixto", "Turístico"] },
      { key: "direccion_exacta", label: "Dirección exacta", type: "text", required: true },
      { key: "barrio_zona", label: "Barrio / Zona", type: "text" },
      { key: "superficie_total_m2", label: "Superficie total", type: "number", unit: "m²" },
      { key: "superficie_cubierta_m2", label: "Superficie cubierta", type: "number", unit: "m²" },
      { key: "superficie_semicubierta_m2", label: "Superficie semicubierta", type: "number", unit: "m²" },
      { key: "cantidad_de_ambientes", label: "Cantidad de ambientes", type: "number" },
      { key: "cantidad_de_dormitorios", label: "Dormitorios", type: "number" },
      { key: "cantidad_de_baños", label: "Baños", type: "number" },
      { key: "cantidad_de_cocheras", label: "Cocheras", type: "number" },
      { key: "amenities", label: "Amenities", type: "textarea", hint: "Piscina, gimnasio, SUM, etc." },
      { key: "año_de_construccion", label: "Año de construcción", type: "number" },
      { key: "estado_de_conservacion", label: "Estado de conservación", type: "select", options: ["Excelente", "Muy bueno", "Bueno", "Regular", "A refaccionar"] },
      { key: "estado_de_ocupacion", label: "Estado de ocupación", type: "select", options: ["Desocupado", "Ocupado por propietario", "Alquilado", "En construcción"] },
      { key: "valor_de_mercado", label: "Valor de mercado", type: "currency" },
      { key: "valor_de_tasacion", label: "Valor de tasación", type: "currency" },
      { key: "empresa_tasadora", label: "Empresa tasadora", type: "text" },
      { key: "fecha_de_tasacion", label: "Fecha de tasación", type: "date" },
      { key: "renta_actual", label: "Renta actual", type: "currency" },
      { key: "renta_proyectada", label: "Renta proyectada", type: "currency" },
      { key: "gastos_mensuales_estimados", label: "Gastos mensuales estimados", type: "currency" },
      { key: "impuestos_asociados", label: "Impuestos asociados", type: "text" },
      { key: "expensas", label: "Expensas", type: "currency" },
      { key: "habilitaciones", label: "Habilitaciones", type: "text" },
      { key: "uso_actual", label: "Uso actual", type: "text" },
      { key: "uso_proyectado", label: "Uso proyectado", type: "text" },
      { key: "riesgos_del_activo", label: "Riesgos del activo", type: "textarea", required: true },
    ],
    requiredDocuments: [
      { key: "escritura_o_titulo", label: "Escritura o título de propiedad", required: true, accept: ".pdf" },
      { key: "informe_de_dominio", label: "Informe de dominio", required: true, accept: ".pdf" },
      { key: "tasacion_profesional", label: "Tasación profesional", required: true, accept: ".pdf" },
      { key: "fotos_del_inmueble", label: "Fotos del inmueble", required: true, accept: ".jpg,.jpeg,.png,.webp", multiple: true },
    ],
    optionalDocuments: [
      { key: "informe_catastral", label: "Informe catastral", required: false, accept: ".pdf" },
      { key: "plano_aprobado", label: "Plano aprobado", required: false, accept: ".pdf,.dwg" },
      { key: "plano_de_obra", label: "Plano de obra", required: false, accept: ".pdf,.dwg" },
      { key: "certificado_libre_deuda", label: "Certificado de libre deuda", required: false, accept: ".pdf" },
      { key: "habilitaciones_municipales", label: "Habilitaciones municipales", required: false, accept: ".pdf" },
      { key: "contrato_de_alquiler", label: "Contrato de alquiler vigente", required: false, accept: ".pdf" },
      { key: "documentacion_impositiva", label: "Documentación impositiva", required: false, accept: ".pdf" },
      { key: "videos_del_inmueble", label: "Videos del inmueble", required: false, accept: ".mp4,.mov" },
      { key: "renders", label: "Renders / visualizaciones", required: false, accept: ".jpg,.jpeg,.png,.pdf" },
      { key: "documentacion_adicional", label: "Documentación adicional", required: false, accept: ".pdf,.jpg,.png", multiple: true },
    ],
  },
  {
    id: "startups",
    label: "Startups",
    icon: "🚀",
    description: "Empresas emergentes en busca de capital",
    fields: [
      { key: "nombre_de_la_startup", label: "Nombre de la startup", type: "text", required: true },
      { key: "industria", label: "Industria", type: "select", required: true, options: ["Fintech", "Healthtech", "Edtech", "Agtech", "Legaltech", "Proptech", "Logística", "E-commerce", "SaaS", "Marketplace", "IoT", "IA / Machine Learning", "Otro"] },
      { key: "año_de_fundacion", label: "Año de fundación", type: "number", required: true },
      { key: "etapa_del_proyecto", label: "Etapa del proyecto", type: "select", required: true, options: ["Idea", "MVP", "Tracción", "Crecimiento", "Escala"] },
      { key: "problema_que_resuelve", label: "Problema que resuelve", type: "textarea", required: true },
      { key: "solucion_propuesta", label: "Solución propuesta", type: "textarea", required: true },
      { key: "modelo_de_negocio", label: "Modelo de negocio", type: "textarea", required: true },
      { key: "mercado_objetivo", label: "Mercado objetivo", type: "text", required: true },
      { key: "tamaño_del_mercado", label: "Tamaño del mercado", type: "text", hint: "Ej: USD 500M en LATAM" },
      { key: "competencia", label: "Competencia", type: "textarea" },
      { key: "ventaja_competitiva", label: "Ventaja competitiva", type: "textarea", required: true },
      { key: "equipo_fundador", label: "Equipo fundador", type: "textarea", required: true, hint: "Nombre, rol y background de cada fundador" },
      { key: "cantidad_de_empleados", label: "Cantidad de empleados", type: "number" },
      { key: "facturacion_actual", label: "Facturación actual", type: "currency" },
      { key: "facturacion_proyectada", label: "Facturación proyectada", type: "currency" },
      { key: "EBITDA_actual", label: "EBITDA actual", type: "currency" },
      { key: "capital_a_levantar", label: "Capital a levantar", type: "currency", required: true },
      { key: "porcentaje_ofrecido", label: "Porcentaje ofrecido / derecho económico", type: "percent", required: true },
      { key: "roadmap", label: "Roadmap", type: "textarea" },
      { key: "metricas_clave", label: "Métricas clave", type: "textarea", hint: "MRR, usuarios activos, churn, NPS, etc." },
      { key: "clientes_actuales", label: "Clientes actuales", type: "text" },
      { key: "socios_estrategicos", label: "Socios estratégicos", type: "text" },
      { key: "riesgos_del_proyecto", label: "Riesgos del proyecto", type: "textarea", required: true },
    ],
    requiredDocuments: [
      { key: "pitch_deck", label: "Pitch Deck", required: true, accept: ".pdf" },
      { key: "estatuto_o_contrato_social", label: "Estatuto o contrato social", required: true, accept: ".pdf" },
      { key: "documentacion_societaria", label: "Documentación societaria", required: true, accept: ".pdf" },
    ],
    optionalDocuments: [
      { key: "business_plan", label: "Business Plan", required: false, accept: ".pdf" },
      { key: "estados_financieros", label: "Estados financieros", required: false, accept: ".pdf,.xlsx,.csv" },
      { key: "cap_table", label: "Cap Table", required: false, accept: ".pdf,.xlsx" },
      { key: "contratos_relevantes", label: "Contratos relevantes", required: false, accept: ".pdf" },
      { key: "propiedad_intelectual", label: "Propiedad intelectual", required: false, accept: ".pdf" },
      { key: "documentacion_fiscal", label: "Documentación fiscal", required: false, accept: ".pdf" },
      { key: "demo_o_video_pitch", label: "Demo o video pitch", required: false, accept: ".mp4,.mov,.pdf" },
      { key: "documentacion_adicional", label: "Documentación adicional", required: false, accept: ".pdf", multiple: true },
    ],
  },
  {
    id: "energia",
    label: "Energía",
    icon: "⚡",
    description: "Proyectos de generación energética renovable",
    fields: [
      { key: "tipo_de_energia", label: "Tipo de energía", type: "select", required: true, options: ["Solar fotovoltaica", "Solar térmica", "Eólica", "Hidráulica", "Biomasa", "Biogás", "Geotérmica", "Hidrógeno verde", "Otro"] },
      { key: "nombre_del_proyecto", label: "Nombre del proyecto", type: "text", required: true },
      { key: "potencia_instalada", label: "Potencia instalada", type: "text", hint: "Ej: 5 MWp" },
      { key: "potencia_proyectada", label: "Potencia proyectada", type: "text" },
      { key: "tecnologia_utilizada", label: "Tecnología utilizada", type: "text", required: true },
      { key: "etapa_del_proyecto", label: "Etapa del proyecto", type: "select", required: true, options: ["Conceptual", "Ingeniería", "Permisos", "En construcción", "Operativo"] },
      { key: "produccion_anual_estimada", label: "Producción anual estimada", type: "text", hint: "Ej: 8.000 MWh/año" },
      { key: "vida_util_estimada", label: "Vida útil estimada", type: "text", hint: "Ej: 25 años" },
      { key: "comprador_de_energia", label: "Comprador de energía", type: "text" },
      { key: "tarifa_estimada", label: "Tarifa estimada", type: "currency", hint: "USD/MWh" },
      { key: "ingresos_proyectados", label: "Ingresos proyectados", type: "currency" },
      { key: "costos_operativos", label: "Costos operativos", type: "currency" },
      { key: "permisos_obtenidos", label: "Permisos obtenidos", type: "text" },
      { key: "permisos_pendientes", label: "Permisos pendientes", type: "text" },
      { key: "impacto_ambiental", label: "Impacto ambiental", type: "textarea" },
      { key: "riesgos_tecnicos", label: "Riesgos técnicos", type: "textarea", required: true },
      { key: "riesgos_regulatorios", label: "Riesgos regulatorios", type: "textarea" },
    ],
    requiredDocuments: [
      { key: "estudio_tecnico", label: "Estudio técnico / Ingeniería básica", required: true, accept: ".pdf" },
      { key: "estudio_de_factibilidad", label: "Estudio de factibilidad", required: true, accept: ".pdf" },
      { key: "permisos_y_autorizaciones", label: "Permisos y autorizaciones obtenidos", required: true, accept: ".pdf" },
    ],
    optionalDocuments: [
      { key: "estudio_impacto_ambiental", label: "Estudio de impacto ambiental", required: false, accept: ".pdf" },
      { key: "contratos_venta_energia", label: "Contratos de venta de energía (PPA)", required: false, accept: ".pdf" },
      { key: "planos_tecnicos", label: "Planos técnicos", required: false, accept: ".pdf,.dwg" },
      { key: "documentacion_titularidad_predio", label: "Titularidad o arriendo del predio", required: false, accept: ".pdf" },
      { key: "presupuestos_instalacion", label: "Presupuestos de instalación", required: false, accept: ".pdf" },
      { key: "certificaciones_tecnicas", label: "Certificaciones técnicas", required: false, accept: ".pdf" },
      { key: "fotos_del_predio", label: "Fotos del predio", required: false, accept: ".jpg,.jpeg,.png,.webp", multiple: true },
      { key: "documentacion_adicional", label: "Documentación adicional", required: false, accept: ".pdf", multiple: true },
    ],
  },
  {
    id: "commodities",
    label: "Commodities",
    icon: "🌾",
    description: "Materias primas y productos básicos",
    fields: [
      { key: "tipo_de_commodity", label: "Tipo de commodity", type: "select", required: true, options: ["Granos (soja, maíz, trigo)", "Ganado", "Petróleo/Gas", "Minerales", "Metales preciosos", "Azúcar", "Café", "Cacao", "Madera", "Otro"] },
      { key: "descripcion_del_activo", label: "Descripción del activo", type: "textarea", required: true },
      { key: "cantidad_disponible", label: "Cantidad disponible", type: "number", required: true },
      { key: "unidad_de_medida", label: "Unidad de medida", type: "select", options: ["Toneladas", "Barriles", "Kg", "Litros", "Unidades", "Acres", "Ha"] },
      { key: "calidad_o_grado", label: "Calidad o grado", type: "text" },
      { key: "certificaciones", label: "Certificaciones", type: "text" },
      { key: "volumen_de_produccion_anual", label: "Volumen de producción anual", type: "text" },
      { key: "precio_de_referencia", label: "Precio de referencia", type: "currency", required: true },
      { key: "mercado_de_destino", label: "Mercado de destino", type: "text" },
      { key: "almacenamiento", label: "Almacenamiento", type: "text" },
      { key: "logistica", label: "Logística", type: "text" },
      { key: "seguros", label: "Seguros", type: "text" },
      { key: "riesgos_de_precio", label: "Riesgos de precio", type: "textarea", required: true },
      { key: "riesgos_logisticos", label: "Riesgos logísticos", type: "textarea" },
      { key: "riesgos_regulatorios", label: "Riesgos regulatorios", type: "textarea" },
    ],
    requiredDocuments: [
      { key: "certificados_de_calidad", label: "Certificados de calidad", required: true, accept: ".pdf" },
      { key: "documentacion_de_titularidad", label: "Documentación de titularidad", required: true, accept: ".pdf" },
    ],
    optionalDocuments: [
      { key: "certificaciones_de_origen", label: "Certificaciones de origen", required: false, accept: ".pdf" },
      { key: "contratos_compra_venta", label: "Contratos de compra-venta", required: false, accept: ".pdf" },
      { key: "informes_de_stock", label: "Informes de stock", required: false, accept: ".pdf,.xlsx" },
      { key: "informes_de_produccion", label: "Informes de producción", required: false, accept: ".pdf,.xlsx" },
      { key: "polizas_de_seguro", label: "Pólizas de seguro", required: false, accept: ".pdf" },
      { key: "documentacion_logistica", label: "Documentación logística", required: false, accept: ".pdf" },
      { key: "fotos_del_activo", label: "Fotos del activo / depósito", required: false, accept: ".jpg,.jpeg,.png,.webp", multiple: true },
      { key: "documentacion_adicional", label: "Documentación adicional", required: false, accept: ".pdf", multiple: true },
    ],
  },
  {
    id: "arte",
    label: "Arte",
    icon: "🎨",
    description: "Obras de arte y bienes culturales",
    fields: [
      { key: "nombre_de_la_obra", label: "Nombre de la obra", type: "text", required: true },
      { key: "artista", label: "Artista", type: "text", required: true },
      { key: "año_de_creacion", label: "Año de creación", type: "number" },
      { key: "tecnica", label: "Técnica", type: "text", required: true, hint: "Ej: Óleo sobre tela, escultura en bronce" },
      { key: "medidas", label: "Medidas", type: "text", hint: "Ej: 120 x 90 cm" },
      { key: "descripcion_de_la_obra", label: "Descripción de la obra", type: "textarea", required: true },
      { key: "estado_de_conservacion", label: "Estado de conservación", type: "select", required: true, options: ["Excelente", "Muy bueno", "Bueno", "Requiere restauración"] },
      { key: "procedencia", label: "Procedencia", type: "textarea", hint: "Historial de propietarios anteriores" },
      { key: "historial_de_exposiciones", label: "Historial de exposiciones", type: "textarea" },
      { key: "historial_de_ventas", label: "Historial de ventas", type: "textarea" },
      { key: "valor_estimado", label: "Valor estimado", type: "currency", required: true },
      { key: "tasador_o_galeria", label: "Tasador o galería", type: "text", required: true },
      { key: "fecha_de_tasacion", label: "Fecha de tasación", type: "date" },
      { key: "lugar_de_custodia", label: "Lugar de custodia", type: "text", required: true },
      { key: "seguro_existente", label: "Seguro existente", type: "text" },
      { key: "derechos_asociados", label: "Derechos asociados", type: "textarea" },
      { key: "riesgos_del_activo", label: "Riesgos del activo", type: "textarea", required: true },
    ],
    requiredDocuments: [
      { key: "certificado_de_autenticidad", label: "Certificado de autenticidad", required: true, accept: ".pdf" },
      { key: "tasacion_profesional", label: "Tasación profesional", required: true, accept: ".pdf" },
      { key: "fotos_alta_calidad", label: "Fotos de alta calidad (frente y verso)", required: true, accept: ".jpg,.jpeg,.png,.webp", multiple: true },
    ],
    optionalDocuments: [
      { key: "videos_de_la_obra", label: "Videos de la obra", required: false, accept: ".mp4,.mov" },
      { key: "documentacion_procedencia", label: "Documentación de procedencia", required: false, accept: ".pdf" },
      { key: "factura_o_contrato_compra", label: "Factura o contrato de compra", required: false, accept: ".pdf" },
      { key: "poliza_de_seguro", label: "Póliza de seguro", required: false, accept: ".pdf" },
      { key: "documentacion_de_custodia", label: "Documentación de custodia", required: false, accept: ".pdf" },
      { key: "documentacion_adicional", label: "Documentación adicional", required: false, accept: ".pdf", multiple: true },
    ],
  },
  {
    id: "turismo",
    label: "Turismo",
    icon: "🏨",
    description: "Proyectos hoteleros y turísticos",
    fields: [
      { key: "tipo_de_proyecto_turistico", label: "Tipo de proyecto turístico", type: "select", required: true, options: ["Hotel", "Apart Hotel", "Cabañas", "Glamping", "Hostel", "Resort", "Complejo turístico", "Restaurante turístico", "Parque temático", "Otro"] },
      { key: "nombre_del_proyecto", label: "Nombre del proyecto", type: "text", required: true },
      { key: "categoria", label: "Categoría", type: "select", options: ["1 estrella", "2 estrellas", "3 estrellas", "4 estrellas", "5 estrellas", "Sin categoría"] },
      { key: "cantidad_de_habitaciones_o_unidades", label: "Cantidad de habitaciones / unidades", type: "number" },
      { key: "capacidad_total", label: "Capacidad total", type: "number", hint: "Cantidad máxima de huéspedes" },
      { key: "superficie_total", label: "Superficie total", type: "number", unit: "m²" },
      { key: "estado_del_proyecto", label: "Estado del proyecto", type: "select", required: true, options: ["Operativo", "En construcción", "Proyectado", "Refacción"] },
      { key: "ocupacion_historica", label: "Ocupación histórica", type: "percent", hint: "% de ocupación histórica promedio" },
      { key: "tarifa_promedio_ADR", label: "Tarifa promedio ADR", type: "currency", hint: "Average Daily Rate en USD" },
      { key: "RevPAR", label: "RevPAR", type: "currency", hint: "Revenue Per Available Room" },
      { key: "ingresos_historicos", label: "Ingresos históricos", type: "currency" },
      { key: "ingresos_proyectados", label: "Ingresos proyectados", type: "currency", required: true },
      { key: "costos_operativos", label: "Costos operativos", type: "currency" },
      { key: "temporada_alta", label: "Temporada alta", type: "text" },
      { key: "temporada_baja", label: "Temporada baja", type: "text" },
      { key: "amenities", label: "Amenities", type: "textarea" },
      { key: "operador_actual", label: "Operador actual", type: "text" },
      { key: "plan_de_expansion", label: "Plan de expansión", type: "textarea" },
      { key: "riesgos_del_proyecto", label: "Riesgos del proyecto", type: "textarea", required: true },
    ],
    requiredDocuments: [
      { key: "documentacion_de_titularidad", label: "Documentación de titularidad", required: true, accept: ".pdf" },
      { key: "habilitaciones_turisticas", label: "Habilitaciones turísticas", required: true, accept: ".pdf" },
      { key: "fotos_del_proyecto", label: "Fotos del proyecto", required: true, accept: ".jpg,.jpeg,.png,.webp", multiple: true },
    ],
    optionalDocuments: [
      { key: "estados_contables", label: "Estados contables o reportes de ingresos", required: false, accept: ".pdf,.xlsx" },
      { key: "planos", label: "Planos", required: false, accept: ".pdf,.dwg" },
      { key: "videos", label: "Videos", required: false, accept: ".mp4,.mov" },
      { key: "brochure_comercial", label: "Brochure comercial", required: false, accept: ".pdf" },
      { key: "contratos_de_operacion", label: "Contratos de operación", required: false, accept: ".pdf" },
      { key: "permisos_municipales", label: "Permisos municipales", required: false, accept: ".pdf" },
      { key: "documentacion_adicional", label: "Documentación adicional", required: false, accept: ".pdf", multiple: true },
    ],
  },
  {
    id: "ambiental",
    label: "Activos Ambientales",
    icon: "🌿",
    description: "Proyectos de sostenibilidad y economía circular",
    fields: [
      { key: "tipo_de_proyecto_ambiental", label: "Tipo de proyecto ambiental", type: "select", required: true, options: ["Recuperación de basurales", "Planta recicladora", "Economía circular", "Créditos de carbono", "Energía limpia", "Saneamiento ambiental", "Valorización de residuos", "Otro"] },
      { key: "descripcion_del_impacto", label: "Descripción del impacto", type: "textarea", required: true },
      { key: "problema_ambiental_que_resuelve", label: "Problema ambiental que resuelve", type: "textarea", required: true },
      { key: "tecnologia_utilizada", label: "Tecnología utilizada", type: "text", required: true },
      { key: "etapa_del_proyecto", label: "Etapa del proyecto", type: "select", required: true, options: ["Conceptual", "Factibilidad", "Permisos", "En construcción", "Operativo"] },
      { key: "toneladas_de_residuos_a_tratar", label: "Toneladas de residuos a tratar", type: "text", hint: "Toneladas por año estimadas" },
      { key: "reduccion_estimada_de_CO2", label: "Reducción estimada de CO₂", type: "text", hint: "Toneladas de CO₂ eq. por año" },
      { key: "creditos_de_carbono_estimados", label: "Créditos de carbono estimados", type: "text", hint: "Créditos de carbono proyectados por año" },
      { key: "beneficiarios_directos", label: "Beneficiarios directos", type: "text" },
      { key: "beneficiarios_indirectos", label: "Beneficiarios indirectos", type: "text" },
      { key: "modelo_de_ingresos", label: "Modelo de ingresos", type: "textarea", required: true },
      { key: "aliados_publicos_o_privados", label: "Aliados públicos o privados", type: "text" },
      { key: "permisos_ambientales", label: "Permisos ambientales obtenidos", type: "text" },
      { key: "certificaciones", label: "Certificaciones", type: "text" },
      { key: "impacto_social", label: "Impacto social", type: "textarea" },
      { key: "riesgos_ambientales", label: "Riesgos ambientales", type: "textarea", required: true },
      { key: "riesgos_regulatorios", label: "Riesgos regulatorios", type: "textarea" },
    ],
    requiredDocuments: [
      { key: "estudio_de_impacto_ambiental", label: "Estudio de impacto ambiental", required: true, accept: ".pdf" },
      { key: "permisos_ambientales_doc", label: "Permisos ambientales", required: true, accept: ".pdf" },
      { key: "informes_tecnicos", label: "Informes técnicos", required: true, accept: ".pdf" },
    ],
    optionalDocuments: [
      { key: "certificaciones_ambientales", label: "Certificaciones ambientales", required: false, accept: ".pdf" },
      { key: "contratos_con_municipios", label: "Contratos con municipios / entes públicos", required: false, accept: ".pdf" },
      { key: "documentacion_del_predio", label: "Documentación del predio", required: false, accept: ".pdf" },
      { key: "plan_de_gestion_ambiental", label: "Plan de gestión ambiental", required: false, accept: ".pdf" },
      { key: "proyeccion_creditos_carbono", label: "Proyección de créditos de carbono", required: false, accept: ".pdf,.xlsx" },
      { key: "fotos_del_sitio", label: "Fotos del sitio", required: false, accept: ".jpg,.jpeg,.png,.webp", multiple: true },
      { key: "videos_del_sitio", label: "Videos del sitio", required: false, accept: ".mp4,.mov" },
      { key: "documentacion_adicional", label: "Documentación adicional", required: false, accept: ".pdf", multiple: true },
    ],
  },
  {
    id: "infraestructura",
    label: "Infraestructura",
    icon: "🏗️",
    description: "Obras y proyectos de infraestructura pública o privada",
    fields: [
      { key: "tipo_de_infraestructura", label: "Tipo de infraestructura", type: "select", required: true, options: ["Vial (rutas, puentes)", "Portuaria", "Aeroportuaria", "Ferroviaria", "Hidráulica", "Energética", "Telecomunicaciones", "Hospitalaria", "Educativa", "Otro"] },
      { key: "nombre_del_proyecto", label: "Nombre del proyecto", type: "text", required: true },
      { key: "organismo_o_empresa_responsable", label: "Organismo o empresa responsable", type: "text" },
      { key: "estado_del_proyecto", label: "Estado del proyecto", type: "select", required: true, options: ["Conceptual", "Licitación", "Adjudicado", "En construcción", "Operativo"] },
      { key: "presupuesto_total", label: "Presupuesto total", type: "currency", required: true },
      { key: "monto_a_financiar", label: "Monto a financiar", type: "currency", required: true },
      { key: "cronograma_de_obra", label: "Cronograma de obra", type: "text", hint: "Ej: 24 meses desde inicio de obra" },
      { key: "plazo_estimado", label: "Plazo estimado", type: "text" },
      { key: "vida_util", label: "Vida útil", type: "text", hint: "Ej: 30 años" },
      { key: "modelo_de_ingresos", label: "Modelo de ingresos", type: "textarea", required: true },
      { key: "concesion", label: "Concesión", type: "text", hint: "Plazo y condiciones si existe" },
      { key: "contratos_asociados", label: "Contratos asociados", type: "text" },
      { key: "permisos_obtenidos", label: "Permisos obtenidos", type: "text" },
      { key: "permisos_pendientes", label: "Permisos pendientes", type: "text" },
      { key: "impacto_economico", label: "Impacto económico", type: "textarea" },
      { key: "impacto_social", label: "Impacto social", type: "textarea" },
      { key: "riesgos_de_obra", label: "Riesgos de obra", type: "textarea", required: true },
      { key: "riesgos_regulatorios", label: "Riesgos regulatorios", type: "textarea" },
    ],
    requiredDocuments: [
      { key: "proyecto_ejecutivo", label: "Proyecto ejecutivo", required: true, accept: ".pdf" },
      { key: "planos_tecnicos", label: "Planos técnicos", required: true, accept: ".pdf,.dwg" },
      { key: "presupuesto_detallado", label: "Presupuesto detallado", required: true, accept: ".pdf,.xlsx" },
      { key: "estudio_de_factibilidad", label: "Estudio de factibilidad", required: true, accept: ".pdf" },
    ],
    optionalDocuments: [
      { key: "contratos_de_concesion", label: "Contratos de concesión", required: false, accept: ".pdf" },
      { key: "permisos_y_autorizaciones", label: "Permisos y autorizaciones", required: false, accept: ".pdf" },
      { key: "estudio_impacto_ambiental", label: "Estudio de impacto ambiental", required: false, accept: ".pdf" },
      { key: "cronograma_gantt", label: "Cronograma de obra (Gantt)", required: false, accept: ".pdf,.xlsx" },
      { key: "documentacion_legal", label: "Documentación legal", required: false, accept: ".pdf" },
      { key: "documentacion_adicional", label: "Documentación adicional", required: false, accept: ".pdf", multiple: true },
    ],
  },
  {
    id: "agroindustria",
    label: "Agroindustria",
    icon: "🌱",
    description: "Producción agropecuaria e industria agroalimentaria",
    fields: [
      { key: "tipo_de_produccion", label: "Tipo de producción", type: "select", required: true, options: ["Agricultura extensiva", "Agricultura intensiva", "Ganadería bovina", "Ganadería porcina", "Avicultura", "Apicultura", "Fruticultura", "Horticultura", "Forestal", "Agroindustria (procesamiento)", "Otro"] },
      { key: "superficie_total", label: "Superficie total", type: "number", unit: "ha" },
      { key: "superficie_productiva", label: "Superficie productiva", type: "number", unit: "ha" },
      { key: "cultivo_o_actividad", label: "Cultivo o actividad", type: "text", required: true },
      { key: "volumen_de_produccion_anual", label: "Volumen de producción anual", type: "text", required: true },
      { key: "historial_productivo", label: "Historial productivo", type: "textarea" },
      { key: "tecnologia_utilizada", label: "Tecnología utilizada", type: "text" },
      { key: "maquinaria_disponible", label: "Maquinaria disponible", type: "text" },
      { key: "sistema_de_riego", label: "Sistema de riego", type: "text" },
      { key: "certificaciones", label: "Certificaciones", type: "text", hint: "Orgánico, GlobalGAP, SENASA, etc." },
      { key: "mercado_destino", label: "Mercado destino", type: "text", required: true },
      { key: "contratos_de_venta", label: "Contratos de venta existentes", type: "text" },
      { key: "costos_operativos", label: "Costos operativos", type: "currency" },
      { key: "ingresos_proyectados", label: "Ingresos proyectados", type: "currency", required: true },
      { key: "seguro_agricola", label: "Seguro agrícola", type: "text" },
      { key: "riesgos_climaticos", label: "Riesgos climáticos", type: "textarea", required: true },
      { key: "riesgos_de_precio", label: "Riesgos de precio", type: "textarea" },
      { key: "riesgos_productivos", label: "Riesgos productivos", type: "textarea" },
    ],
    requiredDocuments: [
      { key: "documentacion_titularidad", label: "Titularidad o contrato de arrendamiento", required: true, accept: ".pdf" },
      { key: "informes_productivos", label: "Informes productivos históricos", required: true, accept: ".pdf,.xlsx" },
    ],
    optionalDocuments: [
      { key: "certificaciones_agroindustriales", label: "Certificaciones agroindustriales", required: false, accept: ".pdf" },
      { key: "contratos_de_venta_doc", label: "Contratos de venta", required: false, accept: ".pdf" },
      { key: "polizas_de_seguro", label: "Pólizas de seguro agrícola", required: false, accept: ".pdf" },
      { key: "mapas_del_predio", label: "Mapas del predio", required: false, accept: ".pdf,.jpg,.png" },
      { key: "fotos_campo", label: "Fotos del campo / planta", required: false, accept: ".jpg,.jpeg,.png,.webp", multiple: true },
      { key: "documentacion_fiscal", label: "Documentación fiscal", required: false, accept: ".pdf" },
      { key: "documentacion_adicional", label: "Documentación adicional", required: false, accept: ".pdf", multiple: true },
    ],
  },
  {
    id: "propiedad_intelectual",
    label: "Propiedad Intelectual",
    icon: "💡",
    description: "Patentes, marcas, derechos de autor y activos intangibles",
    fields: [
      { key: "tipo_de_activo_intangible", label: "Tipo de activo intangible", type: "select", required: true, options: ["Patente", "Marca registrada", "Derecho de autor", "Software / Código fuente", "Franquicia", "Know-how", "Modelo de utilidad", "Diseño industrial", "Otro"] },
      { key: "titular", label: "Titular", type: "text", required: true },
      { key: "pais_de_registro", label: "País de registro", type: "text", required: true },
      { key: "numero_de_registro", label: "Número de registro / expediente", type: "text", hint: "Número oficial" },
      { key: "estado_legal", label: "Estado legal", type: "select", required: true, options: ["En trámite", "Registrado y vigente", "Vencido", "En disputa"] },
      { key: "fecha_de_presentacion", label: "Fecha de presentación", type: "date" },
      { key: "fecha_de_concesion", label: "Fecha de concesión", type: "date" },
      { key: "vencimiento", label: "Vencimiento", type: "date" },
      { key: "descripcion_del_activo", label: "Descripción del activo", type: "textarea", required: true },
      { key: "uso_comercial_actual", label: "Uso comercial actual", type: "textarea" },
      { key: "ingresos_por_licencias", label: "Ingresos por licencias", type: "currency" },
      { key: "ingresos_proyectados", label: "Ingresos proyectados", type: "currency", required: true },
      { key: "regalias_actuales", label: "Regalías actuales", type: "currency" },
      { key: "regalias_proyectadas", label: "Regalías proyectadas", type: "currency" },
      { key: "contratos_de_licencia", label: "Contratos de licencia vigentes", type: "text" },
      { key: "mercados_donde_opera", label: "Mercados donde opera", type: "text", required: true },
      { key: "porcentaje_de_derechos_a_tokenizar", label: "Porcentaje de derechos a tokenizar", type: "percent", required: true },
      { key: "riesgos_legales", label: "Riesgos legales", type: "textarea", required: true },
      { key: "riesgos_comerciales", label: "Riesgos comerciales", type: "textarea" },
    ],
    requiredDocuments: [
      { key: "titulo_de_registro", label: "Título de registro / Certificado oficial", required: true, accept: ".pdf" },
      { key: "certificados_de_titularidad", label: "Certificados de titularidad", required: true, accept: ".pdf" },
      { key: "documentacion_legal", label: "Documentación legal relevante", required: true, accept: ".pdf" },
    ],
    optionalDocuments: [
      { key: "expediente_de_presentacion", label: "Expediente de presentación", required: false, accept: ".pdf" },
      { key: "contratos_de_licencia_doc", label: "Contratos de licencia vigentes", required: false, accept: ".pdf" },
      { key: "documentacion_royalties", label: "Documentación de royalties", required: false, accept: ".pdf,.xlsx" },
      { key: "informes_de_valuacion", label: "Informes de valuación", required: false, accept: ".pdf" },
      { key: "material_demostrativo", label: "Material demostrativo", required: false, accept: ".pdf,.jpg,.png,.mp4" },
      { key: "documentacion_adicional", label: "Documentación adicional", required: false, accept: ".pdf", multiple: true },
    ],
  },
];

export const COMMON_DOCUMENTS: DocumentDef[] = [
  { key: "documento_identidad_emisor", label: "Documento de identidad del emisor", required: true, accept: ".pdf,.jpg,.jpeg,.png", hint: "DNI, pasaporte o documento equivalente" },
  { key: "constancia_fiscal", label: "Constancia fiscal / CUIT / RUT", required: true, accept: ".pdf", hint: "Constancia de inscripción fiscal vigente" },
  { key: "estatuto_contrato_social", label: "Estatuto o contrato social", required: false, accept: ".pdf", hint: "Si corresponde a persona jurídica" },
  { key: "documentacion_legal_general", label: "Documentación legal general", required: false, accept: ".pdf" },
];

export const PAISES = ["Argentina", "Uruguay", "Brasil", "Chile", "Colombia", "México", "Perú", "España", "Estados Unidos", "Otro"];
export const MONEDAS = ["USD", "ARS", "EUR", "USDC", "USDT", "BRL", "CLP"];
export const ESTADO_PROYECTO_OPTIONS = ["En desarrollo", "Operativo", "En construcción", "Planificación", "Otro"];
