export const SECTORS = [
  { id: "real-estate", icon: "🏠", name: "Real Estate", tag: "Inmobiliario" },
  { id: "startups",    icon: "🚀", name: "Startups",    tag: "Venture"     },
  { id: "energia",     icon: "⚡", name: "Energía",     tag: "Energético"  },
  { id: "commodities", icon: "⛏", name: "Commodities", tag: "Materias Primas" },
  { id: "arte",        icon: "🎨", name: "Arte",        tag: "Arte & Cultura" },
  { id: "turismo",     icon: "🏝", name: "Turismo",     tag: "Hospitalidad" },
  { id: "ambiental",   icon: "🌱", name: "Activos Ambientales", tag: "ESG" },
  { id: "infraestructura", icon: "🏗", name: "Infraestructura", tag: "Infraestructura" },
  { id: "agro",        icon: "🌾", name: "Agroindustria", tag: "Agro"      },
  { id: "ip",          icon: "💡", name: "Propiedad Intelectual", tag: "IP & Tech" },
];

export const MOCK_ASSETS = [
  {
    id: "1",
    name: "Torre Catalinas Norte",
    sector: "real-estate",
    location: "Buenos Aires, Argentina",
    totalValue: 4200000,
    tokenPrice: 100,
    tokensAvailable: 18000,
    tokensTotal: 42000,
    expectedReturn: "8.5%",
    term: "36 meses",
    status: "activo" as const,
    description: "Edificio de oficinas premium en el microcentro porteño. Renta garantizada por contratos vigentes.",
    image: "/assets/real-estate.jpg",
  },
  {
    id: "2",
    name: "Parque Solar Mendoza I",
    sector: "energia",
    location: "Mendoza, Argentina",
    totalValue: 2800000,
    tokenPrice: 50,
    tokensAvailable: 22000,
    tokensTotal: 56000,
    expectedReturn: "11.2%",
    term: "60 meses",
    status: "activo" as const,
    description: "Planta de generación solar de 5MW con contrato de suministro a 20 años.",
    image: "/assets/energia.jpg",
  },
  {
    id: "3",
    name: "Hotel Boutique Bariloche",
    sector: "turismo",
    location: "Bariloche, Argentina",
    totalValue: 1900000,
    tokenPrice: 200,
    tokensAvailable: 4750,
    tokensTotal: 9500,
    expectedReturn: "9.8%",
    term: "48 meses",
    status: "activo" as const,
    description: "Hotel de 40 habitaciones con ocupación promedio del 78% anual.",
    image: "/assets/turismo.jpg",
  },
  {
    id: "4",
    name: "FinAgro Soja Export",
    sector: "agro",
    location: "Córdoba, Argentina",
    totalValue: 950000,
    tokenPrice: 25,
    tokensAvailable: 38000,
    tokensTotal: 38000,
    expectedReturn: "13.5%",
    term: "12 meses",
    status: "preventa" as const,
    description: "Financiamiento de ciclo agrícola de soja con exportación garantizada.",
    image: "/assets/agro.jpg",
  },
  {
    id: "5",
    name: "NeuraTech Series A",
    sector: "startups",
    location: "Buenos Aires, Argentina",
    totalValue: 600000,
    tokenPrice: 10,
    tokensAvailable: 60000,
    tokensTotal: 60000,
    expectedReturn: "Variable",
    term: "Sin plazo fijo",
    status: "preventa" as const,
    description: "Startup de IA aplicada a salud. Ronda seed cerrada. Apertura Series A.",
    image: "/assets/startup.jpg",
  },
  {
    id: "6",
    name: "Créditos de Carbono Patagonia",
    sector: "ambiental",
    location: "Santa Cruz, Argentina",
    totalValue: 750000,
    tokenPrice: 15,
    tokensAvailable: 50000,
    tokensTotal: 50000,
    expectedReturn: "10.1%",
    term: "24 meses",
    status: "activo" as const,
    description: "Proyecto de forestación certificado con emisión de créditos de carbono verificados.",
    image: "/assets/ambiental.jpg",
  },
];

export const COLORS = {
  bg: "#0A0A0A",
  bg2: "#111111",
  copper: "#FF9A00",
  gold: "#D4AF37",
  goldLight: "#FFBE3D",
  text: "#FFFFFF",
  text2: "#A1A1AA",
};
